### ISSUE TITLE
Change default theme

### ISSUE THREAD

**Issue by therustmonk** [gdotdesign/elm-ui#75]
I couldn't find any guide how to attach a new theme.
I can change `defaultTheme` in https://github.com/gdotdesign/elm-ui/blob/development/source/Ui/Styles/Theme.elm directly, but I don't think it's a right way.
How to change it simpler?

Also we should add this information to the documentation.

**Comment by gdotdesign** [comment]
Unfortunately there is no proper way of changing the theme. I'm experimenting with some methods, I'll let you know when I have something to share.

**Comment by therustmonk** [comment]
For theming in my projects I use `var` expression. It works in this fashion:

```css
:root { --bg-color: white; --fg-color: black; }
.theme-noon { --bg-color: grey; --fg-color: blue; }
.theme-dark { --bg-color: black; --fg-color: green; }

component { display: block; background: var(--bg-color); color: var(--fg-color); }
```
The advantage of this approach is that you can mix themes in one layout using classes:

```elm
view =
    div [ class "component theme-dark" ]
        [ div [ class "component" ] [ text "This block uses Dark theme" ]
        , div [ class "component theme-noon" ] [ text "This block uses Noon theme" ]
        ]
```

What about to use this approach? It is compatible with all modern browsers and makes possible to change theme on-the-fly without redundancy of parameters trailing.
